# Sieu tham so cho mo hinh GradientBoostingClassifier
# Thay doi cac gia tri nay giua cac lan chay de thi nghiem (Buoc 1)
n_estimators: 300
learning_rate: 0.15
max_depth: 4
# test trigger Fri Aug 21 20:12:58 SEAST 2026
